In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data = pd.read_csv("C:\\Users\\bhand\\OneDrive\\Desktop\\Quantifying the World\\Case Studies\\Case Study 5 -SVM and SGD\\log2.csv")

In [3]:
data = pd.read_csv("C:\\Users\\bhand\\OneDrive\\Desktop\\Quantifying the World\\Case Studies\\Case Study 5 -SVM and SGD\\log2.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65532 entries, 0 to 65531
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Source Port           65532 non-null  int64 
 1   Destination Port      65532 non-null  int64 
 2   NAT Source Port       65532 non-null  int64 
 3   NAT Destination Port  65532 non-null  int64 
 4   Action                65532 non-null  object
 5   Bytes                 65532 non-null  int64 
 6   Bytes Sent            65532 non-null  int64 
 7   Bytes Received        65532 non-null  int64 
 8   Packets               65532 non-null  int64 
 9   Elapsed Time (sec)    65532 non-null  int64 
 10  pkts_sent             65532 non-null  int64 
 11  pkts_received         65532 non-null  int64 
dtypes: int64(11), object(1)
memory usage: 6.0+ MB


In [5]:
df = data
data1 = data
data2=data

In [6]:
data1.head(10)

Source Port  Destination Port  NAT Source Port  NAT Destination Port  \
0        57222                53            54587                    53   
1        56258              3389            56258                  3389   
2         6881             50321            43265                 50321   
3        50553              3389            50553                  3389   
4        50002               443            45848                   443   
5        51465               443            39975                   443   
6        60513             47094            45469                 47094   
7        50049               443            21285                   443   
8        52244             58774             2211                 58774   
9        50627               443            16215                   443   

  Action  Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  \
0  allow    177          94              83        2                  30   
1  allow   4768        1600            3168       19                  17   
2  allow    238         118             120        2                1199   
3  allow   3327        1438            1889       15                  17   
4  allow  25358        6778           18580       31                  16   
5  allow   3961        1595            2366       21                  16   
6  allow    320         140             180        6                   7   
7  allow   7912        3269            4643       23                  96   
8  allow     70          70               0        1                   5   
9  allow   8256        1674            6582       31                  75   

   pkts_sent  pkts_received  
0          1              1  
1         10              9  
2          1              1  
3          8              7  
4         13             18  
5         12              9  
6          3              3  
7         12             11  
8          1              0  
9         15             16

In [7]:
valuesp = df['Source Port'].value_counts()
valuesp.quantile(0.4)

1.0

In [8]:
df = data
data1 = data
data2=data

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65532 entries, 0 to 65531
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype 
---  ------                --------------  ----- 
 0   Source Port           65532 non-null  int64 
 1   Destination Port      65532 non-null  int64 
 2   NAT Source Port       65532 non-null  int64 
 3   NAT Destination Port  65532 non-null  int64 
 4   Action                65532 non-null  object
 5   Bytes                 65532 non-null  int64 
 6   Bytes Sent            65532 non-null  int64 
 7   Bytes Received        65532 non-null  int64 
 8   Packets               65532 non-null  int64 
 9   Elapsed Time (sec)    65532 non-null  int64 
 10  pkts_sent             65532 non-null  int64 
 11  pkts_received         65532 non-null  int64 
dtypes: int64(11), object(1)
memory usage: 6.0+ MB


In [10]:
# classify rare source port with sigle occuring values

df['Source Port'] = df['Source Port'].where(df['Source Port'].map(df['Source Port'].value_counts()) > 1, 'rare_source_port')
df['Source Port'].nunique()

13623

In [11]:
# Now Destination Port
df['Destination Port'] = df['Destination Port'].where(df['Destination Port'].map(df['Destination Port'].value_counts()) > 1, 'rare_destination_port')

In [12]:
# NAT Source Port
df['NAT Source Port'] = df['NAT Source Port'].where(df['NAT Source Port'].map(df['NAT Source Port'].value_counts()) > 1, 'rare_nat_source_port')

In [13]:
# NAT Destination Port
df['NAT Destination Port'] = df['NAT Destination Port'].where(df['NAT Destination Port'].map(df['NAT Destination Port'].value_counts()) > 1, 'rare_nat_destination_port')

In [14]:
# One-hot encoding

from sklearn.preprocessing import LabelEncoder

#  encode the 'Action' column
le = LabelEncoder()
df['Action'] = le.fit_transform(df['Action'])

# One-hot encode the port columns with 0 and 1 
coded_df = pd.get_dummies(df, columns=['Source Port', 'Destination Port', 'NAT Source Port', 'NAT Destination Port'], 
                          prefix=['Source_Port', 'Destination_Port', 'NAT_Source_Port', 'NAT_Destination_Port'], 
                          dtype=int)



coded_df.head()

Action  Bytes  Bytes Sent  Bytes Received  Packets  Elapsed Time (sec)  \
0       0    177          94              83        2                  30   
1       0   4768        1600            3168       19                  17   
2       0    238         118             120        2                1199   
3       0   3327        1438            1889       15                  17   
4       0  25358        6778           18580       31                  16   

   pkts_sent  pkts_received  Source_Port_0  Source_Port_20  ...  \
0          1              1              0               0  ...   
1         10              9              0               0  ...   
2          1              1              0               0  ...   
3          8              7              0               0  ...   
4         13             18              0               0  ...   

   NAT_Destination_Port_64722  NAT_Destination_Port_64745  \
0                           0                           0   
1                           0                           0   
2                           0                           0   
3                           0                           0   
4                           0                           0   

   NAT_Destination_Port_64828  NAT_Destination_Port_64853  \
0                           0                           0   
1                           0                           0   
2                           0                           0   
3                           0                           0   
4                           0                           0   

   NAT_Destination_Port_64923  NAT_Destination_Port_65054  \
0                           0                           0   
1                           0                           0   
2                           0                           0   
3                           0                           0   
4                           0                           0   

   NAT_Destination_Port_65128  NAT_Destination_Port_65253  \
0                           0                           0   
1                           0                           0   
2                           0                           0   
3                           0                           0   
4                           0                           0   

   NAT_Destination_Port_65387  NAT_Destination_Port_rare_nat_destination_port  
0                           0                                               0  
1                           0                                               0  
2                           0                                               0  
3                           0                                               0  
4                           0                                               0  

[5 rows x 23343 columns]

In [15]:
coded_df.shape

(65532, 23343)

In [16]:
from sklearn.model_selection import train_test_split


X = coded_df.drop('Action', axis=1)
y = coded_df['Action']

# Split the data into training and test sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=100)

In [32]:
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.sparse import csr_matrix
import numpy as np

# dataset to a sparse matrix
X_train_sparse = csr_matrix(X_train)  


# parameter grid for SGD
param_grid = {
    'loss': ['hinge', 'log_loss'],
    'alpha': np.logspace(-4, -2, 5),
    'learning_rate': ['constant', 'optimal'],
    'eta0': [0.001, 0.01],  
    'penalty': ['l2', 'elasticnet'],
    'max_iter': [1000],
    'early_stopping': [True]
}

# SGD model
sgd = SGDClassifier(random_state=100)

# Perform Randomized Search with cross-validation
random_search = RandomizedSearchCV(sgd, param_distributions=param_grid, n_iter=40, cv=3, scoring='accuracy', n_jobs=1)
random_search.fit(X_train_sparse, y_train)

# Display best parameters and score
print("Best Parameters:", random_search.best_params_)
print("Best Cross-validation Score:", random_search.best_score_)


Best Parameters: {'penalty': 'l2', 'max_iter': 1000, 'loss': 'log_loss', 'learning_rate': 'optimal', 'eta0': 0.01, 'early_stopping': True, 'alpha': 0.001}
Best Cross-validation Score: 0.9958226037195993


In [33]:
# results from the randomized search
results = random_search.cv_results_

# ataFrame for easy viewing and sorting
import pandas as pd

all_results = pd.DataFrame({
    'Params': results['params'],
    'Mean Test Score': results['mean_test_score'],
    'Std Test Score': results['std_test_score'],
    'Rank': results['rank_test_score']
})

# Sort by rank to see best-performing parameter combinations at the top
all_results_sorted = all_results.sort_values(by='Rank')
print(all_results_sorted)


                                               Params  Mean Test Score  \
26  {'penalty': 'l2', 'max_iter': 1000, 'loss': 'l...         0.995823   
29  {'penalty': 'l2', 'max_iter': 1000, 'loss': 'l...         0.995823   
20  {'penalty': 'elasticnet', 'max_iter': 1000, 'l...         0.995670   
37  {'penalty': 'elasticnet', 'max_iter': 1000, 'l...         0.995613   
8   {'penalty': 'l2', 'max_iter': 1000, 'loss': 'l...         0.994964   
27  {'penalty': 'elasticnet', 'max_iter': 1000, 'l...         0.994030   
17  {'penalty': 'elasticnet', 'max_iter': 1000, 'l...         0.984721   
6   {'penalty': 'l2', 'max_iter': 1000, 'loss': 'l...         0.984568   
33  {'penalty': 'elasticnet', 'max_iter': 1000, 'l...         0.982432   
23  {'penalty': 'l2', 'max_iter': 1000, 'loss': 'h...         0.980525   
14  {'penalty': 'l2', 'max_iter': 1000, 'loss': 'h...         0.980525   
36  {'penalty': 'elasticnet', 'max_iter': 1000, 'l...         0.976748   
25  {'penalty': 'elasticnet', 'max_ite

In [35]:
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

#  SGD model with the best parameters
best_sgd = SGDClassifier(
    penalty='l2',
    max_iter=1000,
    loss='log_loss',
    learning_rate='optimal',
    eta0=0.01,
    early_stopping=True,
    alpha=0.001,
    random_state=100
)

# cross-validation and get scores for each fold
cv_scores = cross_val_score(best_sgd, X_train, y_train, cv=5, scoring='accuracy')
print("Cross-validation scores:", cv_scores)
print("Mean cross-validation score:", np.mean(cv_scores))

# Fit the model 
best_sgd.fit(X_train, y_train)
y_pred = best_sgd.predict(X_train)

# Generate classification report and confusion matrix for the full data
print("\nClassification Report:")
print(classification_report(y_train, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_train, y_pred))


Cross-validation scores: [0.72951836 0.74554125 0.94353839 0.57405818 0.94506438]
Mean cross-validation score: 0.7875441106342393

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.96      0.98     30096
           1       1.00      0.98      0.99     12015
           2       1.00      1.00      1.00     10267
           3       0.00      0.00      0.00        47

    accuracy                           0.97     52425
   macro avg       0.75      0.74      0.74     52425
weighted avg       0.99      0.97      0.98     52425


Confusion Matrix:
[[29003    12     0  1081]
 [  131 11787    36    61]
 [    0     0 10267     0]
 [   10    37     0     0]]
